#!/bin/bash
set -e

# SpotiFLAC Install Script for Linux (Arch/Omarchy)

APP_NAME="SpotiFLAC"
BINARY_NAME="spotiflac" # Final installed name
BUILD_OUTPUT_NAME="SpotiFLAC" # Name generated by Wails
ICON_SOURCE="build/appicon.png"

INSTALL_BIN="$HOME/.local/bin"
# Detect Omarchy specific bin path
if [ -d "$HOME/.local/share/omarchy/bin" ]; then
    INSTALL_BIN="$HOME/.local/share/omarchy/bin"
fi
INSTALL_APPS="$HOME/.local/share/applications"
INSTALL_ICONS="$HOME/.local/share/icons/hicolor/512x512/apps"

echo "Installing $APP_NAME to $INSTALL_BIN..."

# Check for headless flag
HEADLESS=false
for arg in "$@"; do
    if [ "$arg" == "--headless" ]; then
        HEADLESS=true
        shift
    fi
done

# 1. Build
if [ "$HEADLESS" = true ]; then
    echo "Building Headless Mode (CLI only)..."
    go build -tags headless -o "$BINARY_NAME" .
    BUILD_BIN="./$BINARY_NAME"
elif command -v wails &> /dev/null; then
    echo "Building with Wails..."
    wails build
    BUILD_BIN="build/bin/$BUILD_OUTPUT_NAME"
else
    echo "Wails not found, trying standard go build..."
    echo "Warning: This assumes frontend assets are already generated in frontend/dist"
    # Build current directory, defaulting to GUI (!headless) unless tags specified
    go build -o "$BINARY_NAME" .
    BUILD_BIN="./$BINARY_NAME"
fi

if [ ! -f "$BUILD_BIN" ]; then
    echo "Error: Build failed. Binary $BUILD_BIN not found."
    exit 1
fi

# 2. Install Binary
# Aggressively remove from common paths to avoid PATH shadowing issues
rm -f "$HOME/.local/bin/$BINARY_NAME" "$HOME/.local/bin/$APP_NAME"
mkdir -p "$INSTALL_BIN"
rm -f "$INSTALL_BIN/$BINARY_NAME" "$INSTALL_BIN/$APP_NAME" # Force remove target location
cp "$BUILD_BIN" "$INSTALL_BIN/$BINARY_NAME"
echo "Installed binary to $INSTALL_BIN/$BINARY_NAME"


# Verify installation matches build
BUILT_HASH=$(md5sum "$BUILD_BIN" | awk '{print $1}')
INSTALLED_HASH=$(md5sum "$INSTALL_BIN/$BINARY_NAME" | awk '{print $1}')

if [ "$BUILT_HASH" != "$INSTALLED_HASH" ]; then
    echo "Error: Installed binary hash ($INSTALLED_HASH) does not match build ($BUILT_HASH)!"
    exit 1
fi

# 3. Install Icon
mkdir -p "$INSTALL_ICONS"
if [ -f "$ICON_SOURCE" ]; then
    cp "$ICON_SOURCE" "$INSTALL_ICONS/$BINARY_NAME.png"
    echo "Installed icon to $INSTALL_ICONS/$BINARY_NAME.png"
else
    echo "Warning: Icon not found at $ICON_SOURCE"
fi

# 4. Create Desktop Entry
mkdir -p "$INSTALL_APPS"
cat > "$INSTALL_APPS/$BINARY_NAME.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=$APP_NAME
Comment=Spotify Downloader
Exec=$INSTALL_BIN/$BINARY_NAME
Icon=$BINARY_NAME
Terminal=false
Categories=Audio;Network;
Keywords=Spotify;Downloader;Music;
EOF

echo "Created desktop entry at $INSTALL_APPS/$BINARY_NAME.desktop"

# 5. Create Symlink (Shadow system binary)
# User may be accustomed to typing SpotiFLAC
ln -sf "$INSTALL_BIN/$BINARY_NAME" "$INSTALL_BIN/$APP_NAME"
echo "Created symlink $INSTALL_BIN/$APP_NAME -> $BINARY_NAME"

# 6. Refresh
echo "Refreshing desktop database..."
update-desktop-database "$INSTALL_APPS" 2>/dev/null || true

echo "Done! You strictly might need to log out/in or run 'r' in Hyprland/etc for the icon to appear."
